# Generated by Django 3.1.4 on 2021-05-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='con_password',
        ),
        migrations.AlterField(
            model_name='registration',
            name='id_proof',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.ImageField(null=True, upload_to='id/'),
        ),
    ]
